# Generated by Django 5.0.6 on 2024-07-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, choices=[('کاردانی', 'کاردانی نرم افزار'), ('کارشناسی', 'کارشناسی نرم افزار'), ('شبکه', 'شبکه و سخت و افزار')], max_length=200),
        ),
    ]
