# Generated by Django 5.0.6 on 2024-07-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name=' گیت هاب'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name=' لینکدین'),
        ),
    ]
