# Generated by Django 5.0.6 on 2024-06-07 20:47

import django.db.models.deletion
import django_editorjs_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('body', django_editorjs_fields.fields.EditorJsJSONField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pub', 'published'), ('crf', 'crafted')], max_length=50)),
                ('slug', models.SlugField()),
                ('views', models.IntegerField()),
                ('upvote', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
