# Generated by Django 5.0.6 on 2024-06-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_description_article_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
    ]
